# Auto-generated by setup_macros.py - DO NOT COMMIT
JEPAWM_DSET = "/workspace/wm_exp/datasets"
JEPAWM_LOGS = "/workspace/wm_exp/logs"
JEPAWM_HOME = "/workspace/wm_exp"
JEPAWM_OSSCKPT = "/workspace/wm_exp/pretrained_opensource_encoders"
JEPAWM_CKPT = "/workspace/wm_exp/checkpoints"
